### ISSUE TITLE
Candlestick Dashboard looks off

### ISSUE THREAD

**Issue by ebrillhart** [FormidableLabs/victory-docs#151]
@boygirl just a heads up that the Candlestick Dashboard demo seems to be on the fritz - the bars are all running into each other and the area chart isn't offsetting like it used to. Not sure what changes to the codebase might have led to this but noticed it and just wanted to make sure you were aware! I can hop in and change it if that's easier but likely not until later this week/next week.

**Comment by paulathevalley** [comment]
@ebrillhart Is this related to https://github.com/FormidableLabs/victory-docs/issues/111 ?

**Comment by ebrillhart** [comment]
@paulathevalley nope, weirdly a different issue
