### ISSUE TITLE
Docs on webpack builds with Victory

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#24]
_From @knowbody on January 3, 2016 17:51_

Write a comprehensive guide of how to build Victory components in your project with webpack the "right" way considering:
- Source Maps
- Overall build composition
- Pointing to `lib/` vs. `src/`
- Dependency management and flattening for things like lodash, React, et.c

This should go in the main victory README.

_Copied from original issue: FormidableLabs/victory#145_

**Comment by boygirl** [comment]
_From @coopy on January 20, 2016 21:37_

Closing - `npm3` requirement is in docs

**Comment by boygirl** [comment]
_From @ryan-roemer on January 21, 2016 0:8_

@coopy -- This is supposed to be a comprehensive guide of how to build Victory components in your project with webpack the "right" way considering:

* Source Maps
* Overall build composition
* Pointing to `lib/` vs. `src/`
* Dependency management and flattening for things like lodash, React, et.c

Do we have all that already?

**Comment by boygirl** [comment]
_From @coopy on January 21, 2016 0:29_

Ah, I interpreted the issue as just a followup to https://github.com/FormidableLabs/victory/issues/144, which was a `npm2` based issue. Reopening. Thanks for the details!

**Comment by boygirl** [comment]
_From @coopy on March 8, 2016 22:13_

- Roll up #146 into this (build from `src/` not `lib/`)
- Also do #151 as part of this (`npm link` instructions)

**Comment by paulathevalley** [comment]
Hi team! What’s the status on this issue? Is it still relevant? If yes, who will be on point for writing it?

**Comment by ryan-roemer** [comment]
@paulathevalley -- We should roll this work into https://github.com/FormidableLabs/victory/issues/256
