### ISSUE TITLE
confusion around `dataComponent`, `groupComponent` etc. naming

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#242]
See issue:
https://github.com/FormidableLabs/victory/issues/453

**Comment by boygirl** [comment]
This is not a docs issue

**Comment by smith-kyle** [comment]
> This is not a docs issue

Do you mean it's an API issue and these prop types should be components rather than elements? I'd be willing to make this change if you'd accept a PR

**Comment by boygirl** [comment]
@smith-kyle nope, the issue is just that props named things like `dataComponent` should more appropriately be named `dataComponentInstance`, or maybe `dataComponentTemplate` since the component instances are always cloned with additional props. Anyway. We decided to stick with the original naming to avoid a breaking change, and we have since added docs examples in the form `dataComponent={<Bar/>}` etc. that make it clear that a component instance is expected. Thanks for offering to help out, though!
