### ISSUE TITLE
Document evented container limitation

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#276]
Evented container components like `VictoryZoomContainer` only work `standalone={true}`

**Comment by chrisbolin** [comment]
`victory-native`: we only wrap in a `View` if standalone, so we don't handle the non-standalone case at all.
`victory`: this was reported in https://github.com/FormidableLabs/victory/issues/539

**Comment by boygirl** [comment]
closed by https://github.com/FormidableLabs/victory-docs/pull/283/files
