### ISSUE TITLE
/guides pages should have anchor tags

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#286]
Currently /docs pages have linkable anchor tags. /guides should too. This will probably require a change to ecology

**Comment by boygirl** [comment]
https://github.com/FormidableLabs/victory-docs/issues/198

**Comment by ianwsperber** [comment]
Docs for `marked` custom renderer, which @paulathevalley mentioned in #198: https://github.com/chjj/marked#overriding-renderer-methods

**Comment by ianwsperber** [comment]
I think we can reuse the anchor logic in the [markdown component](https://github.com/FormidableLabs/victory-docs/blob/master/src/components/markdown.js#L56) to create a customer header renderer (see above) for the [guide component](https://github.com/FormidableLabs/victory-docs/blob/master/src/screens/guides/components/guide.js#L13)
