### ISSUE TITLE
Victory lander should be searchable

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#287]
https://www.algolia.com/ ?

**Comment by paulathevalley** [comment]
designz
![search1](https://cloud.githubusercontent.com/assets/768965/25685473/8e05422c-301c-11e7-8b73-161cb8f83d2d.png)

![search2](https://cloud.githubusercontent.com/assets/768965/25685474/90e1f95e-301c-11e7-95b0-fbc274bed077.png)

**Comment by boygirl** [comment]
Search will attempt to match the list of common props _first_ so that we don't open every list of props in the sidebar when someone types "style" for example.

**Comment by boygirl** [comment]
see common props issue https://github.com/FormidableLabs/victory-docs/issues/303
