### ISSUE TITLE
Thumbnail gallery of examples

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#289]
The most requested feature in the gitter channel is a list of quick examples. I maintain a list of jsfiddles, but this should really be something provided by the docs.

**Comment by paulathevalley** [comment]
Design:
![blocks_v1](https://cloud.githubusercontent.com/assets/768965/25677866/86edce7a-2ffc-11e7-8a0b-c7a7e1ca3a31.png)
