### ISSUE TITLE
Can we make update-project a no-op?

### ISSUE THREAD

**Issue by chrisbolin** [FormidableLabs/victory-docs#370]
I don't know the full history here, so forgive my ignorance.

This repo uses builder-docs-archetype and its script [build-static](https://github.com/FormidableLabs/builder-docs-archetype/blob/master/package.json#L7):
`builder run clean-static && builder run update-project && builder run webpack-static && builder run copy-assets`

I don't understand the purpose of the mandatory `update-project` call, which in this repo is `npm update victory`. As I see it, what this effectively does is _force the latest version of victory on the project at build time_. It's bad enough that the version is forced upon me (as opposed to just following package.json + yark.lock), but then it happens at production build time, after I've ostensibly already tested in dev mode (which doesn't force this update).

Is the point is to ensure the docs use the most up-to-date version of the package they are documenting? If that's the case, maybe there is an easier and less intrusive way; e.g. we could write a test that compares the local version of victory (`yarn list victory`) with the published version of victory (`yarn info victory version`) and fails if they aren't equal.

What I'd like to do for victory-docs is just make update-project a no-op, and upgrade victory explicitly just like any other dependency.

Of course, this pattern is [really really common](https://github.com/search?utf8=%E2%9C%93&q=update-project+org%3AFormidableLabs+extension%3Ajson&type=Code) in our repos, so I must be missing something here 😞

**Comment by chrisbolin** [comment]
probably a good question for @ryan-roemer or @paulathevalley... or both! 🎈

**Comment by paulathevalley** [comment]
@chrisbolin Yes, I believe your understanding is correct. I remember working with @david-davidson specifically on this task, so he may be able to speak to it better. 

When dox-squad was switching between multiple `*-docs` repos in a single day, we would often run into a problem of publishing the site with outdated modules and having to republish, which was just an incredibly inefficient use of time. This task forced our modules to be updated without relying on our memory to do so. (There were also cases of inexplicable weird local state that `npm update` helped to avoid, too, if I recall correctly.)

My understanding of `npm update` was that it would do nothing if your packages were already up to date. In which case, I wouldn’t classify it as intrusive, but I could be wrong. Is there something else happening? 

All that said, I have no problem with you removing the `update-project` task from `victory-docs`: all the archetype does is echo a statement that it’s missing, but it shouldn’t stop the build. Replacing it with a test sounds stellar :star2:

**Comment by chrisbolin** [comment]
rock on! thanks @paulathevalley!
