### ISSUE TITLE
Add FAQs page

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#380]
FAQs:

- How can I format my axis labels?
- How can I change the colors of lines and other elements in Victory?
- How can I style axes in VictoryChart?
- Why are my labels cut off?
- How can I add tooltips to a line?
- How can I add my own events when I'm using VictoryTooltip?

**Comment by scotmatson** [comment]
- Why is my dependingAxis label overlapping my dependentAxis tickLabels?
- How can I remove the axis from a chart and only display the graphics?

**Comment by hellais** [comment]
* Why are my bars in my bar chart overlapping with the axis?
* How do I get `VictoryVoronoiContainer` to work with `VictoryTooltip` (maybe already covered by how can I add tooltips to a line)?
* How do I add my own custom graphics to the chart (ex. a watermark or a logo)?
* Does  `VictoryChart` support server-side rendering with something like `next.js`?
* How do I make my charts exportable (save as image)?
* How do I make tooltips always visible?

**Comment by boygirl** [comment]
FAQs implementation requirements:
- FAQs should be ecology docs so that we can have live examples
- FAQs should be linked from the nav and from the sidebar
- FAQs should be a single page
- FAQs headings should be searchable in the sidebar like headings for docs and guides
