### ISSUE TITLE
Props style is misplaced

### ISSUE THREAD

**Issue by ch3rn0v** [FormidableLabs/victory-docs#391]
Hello. In the [cursorLabelComponent documentation](https://formidable.com/open-source/victory/docs/victory-cursor-container/#cursorlabelcomponent) I can see that the props style is misplaced:
![misplaced_prop_styles](https://user-images.githubusercontent.com/1066109/28174773-20d06332-67fb-11e7-9044-b88a9cd84b6a.png)
However when I clone the project https://github.com/FormidableLabs/victory-docs and run it locally I can see that those props are styled correctly.
I guess production version should be updated.

**Comment by boygirl** [comment]
@ch3rn0v yes, probably we just need to redeploy
