### ISSUE TITLE
Make documentation 'scroll wheel' friendly

### ISSUE THREAD

**Issue by wijnsema** [FormidableLabs/victory-docs#433]
When you browse through the documentation, the LIVE PREVIEW and EDITABLE SOURCE div's are full width. This makes scrolling through the page with the mouse wheel stop at every example source div (scrolling continues inside this div). This is a real nuisance. Tested in Chrome and Edge.

Please maximize the width, just a you maximize the width of the text. As a reader I can then simply choose which part I want to scroll by positioning my mouse to the right of the page (which scrolls the page) or above the source (which scrolls the source).

Added bonus: this look better!

Kind regards, Ronald Wijnsema

**Comment by boygirl** [comment]
@wijnsema Thanks for the suggestion. This change is reflected in the latest docs update

**Comment by wijnsema** [comment]
Thanks Lauren!
Tried it out, works really well now!
Ronald
