### ISSUE TITLE
Bug in chart in Events documentation

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#434]
_From @wijnsema on October 5, 2017 9:26_

The first chart in the documentation about Events at 
https://formidable.com/open-source/victory/guides/events/
is not reacting to the second and third mouse click, if you click the same bar. At the fourth click on the same bar everything seems to be working well. If you refresh the page everything starts over again.

_Copied from original issue: FormidableLabs/victory#783_

**Comment by wijnsema** [comment]
The documentation is just to reproduce. I think this is a bug in the chart library.
