### ISSUE TITLE
Make header shrink on scroll

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#472]
Victory docs pages have a large hero header, which gets in the way when reading the documentation. It's a fine experience before scrolling, but when the user scrolls down, the header should get out of the way (shrink vertically) to maximize reading real estate.

SIde issue: The header is individually scrollable, but should be non-scrollable.

See below screen cap for an illustration of both issues.

![victory-docs](https://user-images.githubusercontent.com/794843/40672485-cf082966-6323-11e8-9cd2-81c41596cdce.gif)

**Comment by coopy** [comment]
The new header works much better! However, I think it should be static on all pages, including Home, About, and Gallery. What do you think @boygirl?

**Comment by boygirl** [comment]
Yes, I will correct the inconsistency
