### ISSUE TITLE
Make this repo public again

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory-docs#51]
In the process of setting up automatic deployment, this repo was made private. However, it should (and can) be made public again!

This may require reconfiguring travis’s encrypted environment key that access the formidable.com server. 

### Instructions for Travis 

To hookup travis, first, convert the SSH key to `.pem` format:

```sh 
openssl rsa -in id_rsa -out deploy_static.pem
```

Then, [encrypt the key with the travis gem](https://docs.travis-ci.com/user/encrypting-files/), which will generate encrypted environment variables on travis. It will modify the `.travis.yml` file to add the decryption step, and any comments/formatting will be lost. (Note: encrypted environment variables are not available for pull requests from forks.)

```
gem install travis
travis encrypt-file ~/.ssh/deploy_static.pem --add
```

Make sure the `.travis.yml` configuration file does not preserve any of the filepath, e.g. `~/.ssh/` from the example above.

**Comment by chrisbolin** [comment]
Done :)
