### ISSUE TITLE
Multiple dependent Axis for React Native

### ISSUE THREAD

**Issue by priyanga2496** [FormidableLabs/victory-docs#560]
How to pass diferent domain values to multiple dependent axis in victory line chart, there is option which takes large domain assigned to both y axis. could you help me with assigning diferent domain for dependent y axis ? Examples given are only for React using <div> and <svg> which is not suported in React Native

**Comment by priyanga2496** [comment]
@boygirl kindly have a look on above mentioned issue

**Comment by boygirl** [comment]
@priyanga2496 VictoryNative and Victory have the same API, so you can change where you are importing the components from and it should work identically. 
Just change:
```
import { VictoryChart, VictoryLine } from "victory";
```
to 
```
import { VictoryChart, VictoryLine } from "victory-native";
```

For multiple dependent axes:

`VictoryChart` does not support using a different domain for different children. All children are required to use the same domain. Instead, you can normalize your data and then format your axis ticks. This example demonstrates how to do it: 
https://formidable.com/open-source/victory/gallery/multiple-dependent-axes/
