### ISSUE TITLE
Increase spacing underneath dropdown 

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory-docs#60]
This spacing is a bit tight:
![screen shot 2016-08-01 at 10 50 57 am](https://cloud.githubusercontent.com/assets/768965/17303507/dc682c10-57d5-11e6-98ae-a3461e053b9c.png)

**Comment by chrisbolin** [comment]
Fixed in a restyling that @paulathevalley did :) 
![victorychart___documentation](https://cloud.githubusercontent.com/assets/2822048/17942056/d494352a-6a03-11e6-90d0-c685de543548.jpg)
