### ISSUE TITLE
Issues on how to render Lines on a Chart dynamically

### ISSUE THREAD

**Issue by ElieSol** [FormidableLabs/victory-docs#605]
Hello,

I am new to using ReactJS/TS and currently doing graph with Victory for a project. I have issues on how to render dynamically a Line (i.e. when the user selects an option, a line should appear on a predefined Chart) with Victory.

I have a tried by defining a function like this:
`private LineScomponent(data:any){`
`return(`
`<VictoryGroup
data={data}
color={"Blue"}
x="a"
y="b">`
`<VictoryLine/>`
`<VictoryScatter/>`
`</VictoryGroup>`
`)`
`}`
and adding this in the render (inside `<VictoryChart>` tags):
`<this.LineSComponent data={gene_data}>`
But nothing appears on the Chart...

I have seen the External Event Mutations on Victory's doc, but I don't really know if this could be applied to my case...

Any help/recommendation would be great 

Thank you for your time

**Comment by boygirl** [comment]
@ElieSol you'll probably want to do something with state like so:

```jsx
<VictoryChart>
  <VictoryScatter data={myData} />
  {this.state.renderLine ? <VictoryLine data={lineData} /> : null}
  {this.state.renderLine ? renderMyOtherLine(otherLineData) : null}
</VictoryChart>
```

p.s. in future please ask questions like this one in our spectrum channel: https://spectrum.chat/victory or open an issue in the main victory repo.
