### ISSUE TITLE
Change order / layout of victory components on front page

### ISSUE THREAD

**Issue by eastridge** [FormidableLabs/victory-docs#9]
Suggested layout:

Column 1:
- VictoryCore
- VictoryAnimation

Column 2:
- VictoryChart
- (indented list of chart subcomponents)

Column 3:
- VictoryPie
- (list of components coming soon, greyed out with "coming soon" text)

**Comment by paulathevalley** [comment]
I am working on terminology for each column and could use a sanity check. 

If there is not already a system in place, perhaps Chart and Pie are both _Figures_, and each component that a Figure wraps is called a _Layer_.

Column 1: **Core**
Column 2: **Chart Figure** 
Column 3: **Other Figure** 

For clarity, here is each list: 

**Core**:
- VictoryAnimation
- VictoryCore [need to add its Docs to site]
- VictoryUtil [need to add its Docs to site]

**Chart Figure**:
- VictoryChart and its layers:
  - VictoryArea
  - VictoryAxis
  - VictoryBar
  - VictoryLabel
  - VictoryLine
  - VictoryScatter 

**Other Figures**:
- VictoryPie 
- Other Figure Layers (?):
  - VictoryTooltip [coming soon]
  - VictoryConstraints [coming soon]
  - VictoryStack [coming soon]
  - VictoryGroup [coming soon]

-----------
Reading:
[A layered grammar of graphics](http://vita.had.co.nz/papers/layered-grammar.html) and its implementation in [ggplot2](http://docs.ggplot2.org/current/)

**Comment by paulathevalley** [comment]
If that's too esoteric, then here’s an explicit route which maps to the where everything lives on github:

**Core**:
- VictoryAnimation
- VictoryLabel

**Chart**:
- VictoryChart:
  - VictoryArea
  - VictoryAxis
  - VictoryBar
  - VictoryLine
  - VictoryScatter 
  - VictoryConstraints [coming soon]
  - VictoryGroup [coming soon]
  - VictoryStack [coming soon]
  - VictoryTooltip [coming soon]

**Pie**:
- VictoryPie

**Comment by boygirl** [comment]
VictoryStack and VictoryGroup are already built, and documented within the VictoryArea and VictoryBar docs (where they are useful / supported), but maybe they need their own docs sections?

**Comment by paulathevalley** [comment]
Ah! I see. I would only break them out into their own docs sections if either: 
a.) there are plans to integrate them with more chart layers/sub-components (making it tedious/repetitious to add the same docs to each chart layer/sub-component)
b.) users are confused, or users want more specific, in-depth information on VictoryStack or VictoryGroup

Otherwise I would leave them where they are. :)
