### ISSUE TITLE
Add a Showcase section to the About page

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory-docs#92]
- Showcase page should live in the About page, formidable.com/open-source/victory/about  
- In the repo, it should be a new component at `src/screens/about/components/showcase.js` 
- For each app/usage, there should be:
    - a screenshot 
    - the name of the company that uses it 
    - one or two sentences that provide context: who is using it, how are they using it, and what they are using it for (or whatever context makes the most sense)
- Finally, there should be a link to the showcase on the homepage. Somewhere. Maybe the logos stay on the homepage and there’s a call to action to the showcase. Maybe the showcase link needs to be farther up on the page. I'm not clear on this part yet.

**Comment by paulathevalley** [comment]
Apps screenshots for Showcase: 
- Tune
- Cumul8
- Postmark
- FiveThirtyEight 

@ebrillhart Are there any other screenshots we can use for this section?

**Comment by ebrillhart** [comment]
@paulathevalley that's all that I was made aware of that I could find! Did not get any response on the Gitter channel when I put out a call.
