### ISSUE TITLE
Create an About Victory Page

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory-docs#94]
- The about page should live at formidable.com/open-source/victory/about  
- In the repo, it should be a new component at `src/screens/about/index.js` 
- The page should contain:
    1. Showcase (with an anchor tag so we can link to it directly: formidable.com/open-source/victory/about#showcase)
    2. Origin of Victory story (including photos of the OG Formidable(s)?)
    3. Top 5? 8? contributors pulled from Github
    4. Formidable’s story

**Comment by ebrillhart** [comment]
based on githubs permissions for their API, the one change I would make to this list is that we just link to the contributors page in Github for the repo

**Comment by ebrillhart** [comment]
issue regarding showcase: https://github.com/FormidableLabs/victory-docs/issues/92
